name: Build Python Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Make create_mac_app.sh executable
        run: chmod +x ./scripts/create_mac_app.sh

      - name: Build application
        run: ./scripts/create_mac_app.sh

      - name: Create run.command file
        run: |
          echo 'cd "$(dirname "$0")"' > dist/run.command
          echo 'xattr -d com.apple.quarantine ./eVAS.app' >> dist/run.command
          echo 'rm ./run.command' >> dist/run.command
          chmod +x dist/run.command
          xattr -d com.apple.quarantine dist/run.command

      - name: Create ZIP archive
        run: |
          cd dist
          zip -r eVAS_macos.zip eVAS.app run.command

      - name: Move ZIP archive to macos folder
        run: |
          mkdir -p dist/macos
          mv dist/eVAS_macos.zip dist/macos/eVAS_macos.zip

      - name: Commit and push ZIP archive
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -f dist/macos/eVAS_macos.zip
          git commit -m "Add built application archive"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}